
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">About Admin</h1>
                    </div>
						
			<p>
			Here you can add all the stuff to admin this module. This content can span the entire page fully whilst below are some options if you wish to use a dual column layout for your admin.
			</p>

                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

