	
		<!-- MAIN -->
		<div id="main">
				
			<!-- social -->
			<div id="social-bar">
				<ul>
					<li><a href="http://www.facebook.com"  title="Become a fan"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/facebook_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.twitter.com" title="Follow my tweets"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/twitter_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.google.com"  title="Add to the circle"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/google_plus_32.png" alt="Facebook" /></a></li>
				</ul>
			</div>
			<!-- ENDS social -->
			
			
			
			<!-- Content -->
			<div id="content">
			
				<!-- masthead -->
		        <div id="masthead">
					<span class="head">Blog</span><span class="subhead">this is a sub heading</span>
					<ul class="breadcrumbs">
						<li><a href="index.html">home</a></li>
						<li>/ blog</li>
					</ul>
				</div>
	        	<!-- ENDS masthead -->
	        	
	        	
	        	
	        	<!-- posts list -->
	        	<div id="posts-list">
	        	
					<article class="format-standard">
						
						<div class="feature-image">
							<a href="<?php echo PUBLIC_PATH; ?>/assets/images/slides/01.jpg" data-rel="prettyPhoto"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/slides/01.jpg" alt="Alt text" /></a>
						</div>
						
						<h1><a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="post-heading">Lorem ipsum dolor amet</a></h1>
						<div class="meta">
							<span class="entry-date">23 Sep, 2011</span>
							in <span class="categories"><a href="#">Category 1</a>, <a href="#">Category 2</a></span>
						</div>
						
						
						<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
						</div>
						
						<a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="read-more">read more</a>
						
					</article>
					
					
					<article class="format-standard">
						
						<div class="feature-image">
							<a href="<?php echo PUBLIC_PATH; ?>/assets/images/slides/02.jpg" data-rel="prettyPhoto"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/slides/02.jpg" alt="Alt text" /></a>
						</div>
						
						<h1><a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="post-heading">Lorem ipsum dolor amet</a></h1>
						<div class="meta">
							<span class="entry-day">23</span>
							<span class="entry-year">sep 2011</span>
						</div>
						
						
						<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
						</div>
						
						<a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="read-more">read more</a>
						
					</article>
					
					
					<article class="format-standard">
						
						<div class="feature-image">
							<a href="<?php echo PUBLIC_PATH; ?>/assets/images/slides/03.jpg" data-rel="prettyPhoto"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/slides/03.jpg" alt="Alt text" /></a>
						</div>
						
						<h1><a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="post-heading">Lorem ipsum dolor amet</a></h1>
						<div class="meta">
							<span class="entry-day">23</span>
							<span class="entry-year">sep 2011</span>
						</div>
						
						
						<div class="excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed.
						</div>
						
						<a href="<?php echo PUBLIC_PATH; ?>/blog/show" class="read-more">read more</a>
						
					</article>
	        		
	        		
	        	</div>
	        	<!-- ENDS posts list -->
	        	
	        	
	        	<!-- sidebar -->
	        	<aside id="sidebar">
	        		
	        		<div class="block">
		        		<h4>categories</h4>
						<ul>
							<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
						</ul>
	        		</div>
	        		
	        		<div class="block">
		        		<h4>archives</h4>
						<ul>
							<li class="cat-item"><a href="#" title="View all posts">January</a></li>
							<li class="cat-item"><a href="#" title="View all posts">February</a></li>
							<li class="cat-item"><a href="#" title="View all posts">March</a></li>
						</ul>
	        		</div>
	        	
	        	</aside>
	        	<div class="clearfix"></div>
				<!-- ENDS sidebar -->
				
				
				<!-- pager -->
        		<ul class="pager">
					<li class="paged">Page 1 of 2</li>
					<li class="active"><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
				</ul>
				<div class="clearfix"></div>
	        	<!-- ENDS pager -->
			
			</div>
			<!-- ENDS content -->
			
			<div class="clearfix"></div>
			<div class="shadow-main"></div>
			
			
		</div>
		<!-- ENDS MAIN -->
		
