	
		<!-- MAIN -->
		<div id="main">
				
			<!-- social -->
			<div id="social-bar">
				<ul>
					<li><a href="http://www.facebook.com"  title="Become a fan"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/facebook_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.twitter.com" title="Follow my tweets"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/twitter_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.google.com"  title="Add to the circle"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/google_plus_32.png" alt="Facebook" /></a></li>
				</ul>
			</div>
			<!-- ENDS social -->
			
			
			
			<!-- Content -->
			<div id="content">
			
				<!-- masthead -->
		        <div id="masthead">
					<span class="head">Portfolio</span><span class="subhead">this is a sub heading</span>
					<ul class="breadcrumbs">
						<li><a href="<?php echo PUBLIC_PATH; ?>">home</a></li>
						<li>/ portfolio</li>
					</ul>
				</div>
	        	<!-- ENDS masthead -->
	        	
	        	
	        	
	        	<!-- portfolio list -->
	        	<div class="featured portfolio-list">
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/gallery-1.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/gallery-1.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. 
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-1.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-1.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-2.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-2.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. 
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-3.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-3.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-4.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-4.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. 
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		
	        		<figure>
	        			<a href="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-5.jpg" data-rel="prettyPhoto" class="thumb"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/dummies/featured-5.jpg" alt="Alt text" /></a>
	        			<div>
	        				<a href="project.html" class="heading">Pellentesque habitant morbi</a>
		        			tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. 
		        		</div>
		        		<a class="link" href="project.html"></a>
	        		</figure>
	        		<div class="clearfix"></div>
					        		
	        	</div>
	        	<!-- ENDS featured -->
	        	
	        	
	        	<!-- pager -->
        		<ul class="pager">
					<li class="paged">Page 1 of 2</li>
					<li class="active"><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
				</ul>
				<div class="clearfix"></div>
	        	<!-- ENDS pager -->
	        	
	        	
	        	<aside class="retractil">
	        		<div id="sidebar-opener">categories</div>
	        		<div id="sidebar-closer"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/close.png" alt="close"></div>
	        		<div id="sidebar-content">
						<ul>
							<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Film and video</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Print</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Photo and lomo</a></li>
							<li class="cat-item"><a href="#" title="View all posts">Habitant morbi</a></li>
						</ul>
	        		</div>
	        	</aside>
				
			
			</div>
			<!-- ENDS content -->
			
			<div class="clearfix"></div>
			<div class="shadow-main"></div>
			
			
		</div>
		<!-- ENDS MAIN -->
		
