
    <!-- jQuery -->
    <script src="<?php echo PUBLIC_PATH; ?>/assets/admin/js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo PUBLIC_PATH; ?>/assets/admin/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo PUBLIC_PATH; ?>/assets/admin/js/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="<?php echo PUBLIC_PATH; ?>/assets/admin/js/raphael-min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo PUBLIC_PATH; ?>/assets/admin/js/sb-admin-2.js"></script>
