	
		<!-- MAIN -->
		<div id="main">
				
			<!-- social -->
			<div id="social-bar">
				<ul>
					<li><a href="http://www.facebook.com"  title="Become a fan"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/facebook_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.twitter.com" title="Follow my tweets"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/twitter_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.google.com"  title="Add to the circle"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/google_plus_32.png" alt="Facebook" /></a></li>
				</ul>
			</div>
			<!-- ENDS social -->
			
			
			
			<!-- Content -->
			<div id="content">
			
				<!-- masthead -->
		        <div id="masthead">
					<span class="head">Blog Admin</span><span class="subhead">adminster blog</span>
					<ul class="breadcrumbs">
						<li><a href="<?php echo PUBLIC_PATH; ?>/">home</a></li>
						<li>/ blog admin</li>
					</ul>
				</div>
	        	<!-- ENDS masthead -->
	        	
	        	
	        	
	        	<!-- page content -->
	        	<div id="page-content-full">
	        	
						
					<p>
						Here you can add all the stuff to admin this module. This content can span the entire page fully whilst below are some options if you wish to use a dual column layout for your admin.
					</p>
					
					
					<!-- 2 cols -->
					<div class="one-half">
						<h2 class="heading">Admin Things</h2>
						Here can go some forms or whatever you like to admin this module.
					</div>
					
					<div class="one-half last">
						<h2 class="heading">More Things</h2>
						You can place more forms or whatever you like here. Graphs, statistics or stuff that you may like when using this module admin.
					</div>
					<div class="clearfix"></div>
					<!-- ENDS 2 cols -->
					
					
					<!-- 3 cols -->
					<div class="one-third">
						<h2 class="heading">One third columns</h2>
						If you really need to get creative with your admin layout, you can use three columns.
					</div>
					
					<div class="one-third">
						<h2 class="heading">One third columns</h2>
						If you really need to get creative with your admin layout, you can use three columns.
					</div>
					
					<div class="one-third last">
						<h2 class="heading">One third columns</h2>
						If you really need to get creative with your admin layout, you can use three columns.
					</div>
					<div class="clearfix"></div>
					<!-- ENDS 3 cols -->
					
					<!-- Buttons -->
					<h1 class="h-heading">Buttons</h1>
					<ul class="column">
				        <li>
				          <button class="minimal">Minimal</button>
				        </li>
				        <li>
				          <button class="clean-gray">Clean Gray</button>
				        </li>
				        <li>
				          <button class="cupid-green">Cupid Green</button>
				        </li>
				        <li>
				          <button class="cupid-blue">Cupid Blue</button>
				        </li>
				        <li>
				          <button class="blue-pill">Blue Pill</button>
				        </li>
				        <li>
				          <button class="dribbble">Dribbble</button>
				        </li>
				        <li>
				           <button class="slick-black">Slick Black</button>
				         </li>
				        <li>
				          <button class="thoughtbot">thoughtbot</button>
				        </li>
				        <li>
				          <button class="punch">Punch</button>
				        </li>
				        <li>
				          <button class="blue-candy">Blue Candy</button>
				        </li>
				        <li>
				          <button class="purple-candy">Purple Candy</button>
				        </li>
				        <li>
				          <button class="shiny-blue">Shiny Blue</button>
				        </li>
				        <li>
				          <button class="download-itunes">Download iTunes</button>
				        </li>
				        <li>
				          <button class="skip">Skip</button>
				        </li>
				        <li>
				          <div class="indent"><button class="minimal-indent">Minimal Indent</button></div>
				        </li>
				      </ul>
				      <div class="clearfix"></div>
				      <!-- ENDS Buttons -->
					
	        	</div>
	        	<!-- ENDS page content -->
	        	
	        	
				
				
			
			</div>
			<!-- ENDS content -->
			
			<div class="clearfix"></div>
			<div class="shadow-main"></div>
			
			
		</div>
		<!-- ENDS MAIN -->
		
