	
		<!-- MAIN -->
		<div id="main">
				
			<!-- social -->
			<div id="social-bar">
				<ul>
					<li><a href="http://www.facebook.com"  title="Become a fan"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/facebook_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.twitter.com" title="Follow my tweets"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/twitter_32.png"  alt="Facebook" /></a></li>
					<li><a href="http://www.google.com"  title="Add to the circle"><img src="<?php echo PUBLIC_PATH; ?>/assets/images/social/google_plus_32.png" alt="Facebook" /></a></li>
				</ul>
			</div>
			<!-- ENDS social -->
			
			
			
			<!-- Content -->
			<div id="content">
			
				<!-- masthead -->
		        <div id="masthead">
					<span class="head">Logging</span><span class="subhead">adminstration documentation</span>
					<ul class="breadcrumbs">
						<li><a href="<?php echo PUBLIC_PATH; ?>/">home</a></li>
						<li><a href="<?php echo PUBLIC_PATH; ?>/docs"> / docs</a></li>
						<li>/ layouts</li>
					</ul>
				</div>
	        	<!-- ENDS masthead -->
	        	
	        	
	        	
	        	<!-- page content -->
	        	<div id="page-content-full">
	        	
<p>
Many applications will require more than a single layout for different parts of the display. To this end we have added the ability to change the layout_file in the view. The default layout in the applications/layouts directory is index.phtml. This can now be altered in the controller using the below code.
</p>
</p>
<div class="codebox">
<?php
$code = '
<?php
$this->view->layout_file = \'cart_layout.phtml\';
?>';
highlight_string($code);
?>
</div>
<p>
The above code sets the default layout to the cart_layout.phtml, which will need to alongside the default index.phtml layout in the application/layout directory. This could also be in the controller constructor to make the layout global across all methods in a given controller.
</p>

					
	        	</div>
	        	<!-- ENDS page content -->
				
			
			</div>
			<!-- ENDS content -->
			
			<div class="clearfix"></div>
			<div class="shadow-main"></div>
			
			
		</div>
		<!-- ENDS MAIN -->
		
