<h1>Setup Admin</h1>
<p>
This is the index view page for the setup Module Administration.
</p>
<p>
Here you will put all the administration tasks for the setup module.
</p>
<p>
This file is located in /application/setup/views/admin_index.phtml file
</p>
<p>
Access to this administration file is left to the user, or you may remove the
administration component completely, simply by deleting this file and the
setup_admincontroller.php file.
</p>
