<h1>User Admin</h1>
<p>
This is the index view page for the user Module Administration.
</p>
<p>
Here you will put all the administration tasks for the user module.
</p>
<p>
This file is located in /application/user/views/admin_index.phtml file
</p>
<p>
Access to this administration file is left to the user, or you may remove the
administration component completely, simply by deleting this file and the
user_admincontroller.php file.
</p>
